from pytube import YouTube
link = input("Enter a link: ")
yt: YouTube = YouTube(link)
print("Title: ", yt.title)
print("Number of Veiws: ", yt.views)
print("Length: ", yt.length)
print("rating: ", yt.rating)
print("streams: ", yt.streams)
print("yt.streams.filter(only_video = True)")
print("yt.streams.filter(progressive=True)")
ys=yt.streams.get_highest_resolution()
ys=yt.streams.get_by_itag('22')
print('video is loading...')
location=input("Enter a path: ")
ys.download(location)
print("video completed")